title: hello world
subtitle: null
description: this is a blog
author: Hugh
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
category:
  - code
  - article
category_icon:
  - icon-blog
  - icon-embed
  - icon-blog
  - icon-blog
new_post_name: new.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: null
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: theme-blue
deploy:
  type: git
  repository: ''
  username: ''
  password: ''
  branch: master
link:
  linkin: ''
  email: ''
  weibo: ''
  github: ''
